name: build main branch

on:
  push:
    branches: [ main ]
    paths:
      - "*.go"
  pull_request:
    branches: [ main ]
    paths:
      - "*.go"

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Install make
        run: choco install make

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install proto-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      
      - name: Build
        run: make
  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install proto-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      
      - name: Build
        run: make